### PR TITLE
Fix "tutorial" (typo & verbosity list issue)

### PR DESCRIPTION
**Pull request by Laurae2**
This PR fixes:
- The verbosity error as default in buildEdgeMatrix (it was using a list as default instead of a boolean)
- The typo in the "tutorial" about "buildWijMaatrix" instead of "buildWijMatrix"

### CODE REVIEW

**Comment by elbamos** [comment]
@Laurae2 I'm just seeing this now.  If you want to resubmit this so its against the current master, I'll accept the PR.  Thanks!

**Comment by Laurae2** [comment]
Rebased against master, you can squash and merge all the commits into one while merging as one of your commits was similar to mines.

It leaves all the typos "buildWijMaatrix" fixed in commits (I thought I merged all of them, seems it didn't - you should have squash and merge so it becomes only one commit at the time of merging branches).

I can squash together all the commits myself if the squash & merge is not available in this repo.

**Comment by elbamos** [comment]
Can you clear the CI failures? Also, could you make the pull against branch hdbscan? That's going to be 0.1.8

**Comment by Laurae2** [comment]
Fixed the issue making check failing and changed the pull to hdbscan as requested. Builds are passing.

**Pull request merged**
